Provide prevention measures
osirislab/ctf101 pull request #20
Opened 2024-04-16 18:56 UTC by HiimHyy

Awesome material!
Trying to contribute more to site.

2024-04-19 02:55 UTC, davidchiii submitted a review, later dismissed
great addition! Thanks for contributing

2024-04-23 22:17 UTC, M0rtale requested changes
✨

2024-04-23 22:17 UTC, M0rtale commented on docs/web-exploitation/sql-injection/what-is-sql-injection.md
> +We can also inject comments and termination characters like `--` or `/*` or `;`. This allows you to terminate SQL queries after your injected statements. For example `'--` is a common SQL injection p
block: SQL requires at least 1 space after double dash for a valid comment

https://dev.mysql.com/doc/refman/8.0/en/comments.html#:~:text=In%20MySQL%2C%20the%20%2D%2D%20(double,as%20discussed%20in%20Section%201.6.

2024-04-25 04:30 UTC, HiimHyy reviewed
resolve sql injection example

2024-04-25 04:32 UTC, HiimHyy commented on docs/web-exploitation/sql-injection/what-is-sql-injection.md
> +We can also inject comments and termination characters like `--` or `/*` or `;`. This allows you to terminate SQL queries after your injected statements. For example `'--` is a common SQL injection p
fixed in new commit

2024-04-30 15:27 UTC, davidchiii approved these changes
fixed. thanks @M0rtale :)

2024-04-30 15:28 UTC, M0rtale approved these changes
LGTM

2024-04-30 15:33 UTC, merged